env:
  gitconfigs: "ENCRYPTED[!5ac5f7e17bbdc60d88ddde16c0fa3108b36bc9810a169cccde65cd85733cf7a43288ccb2f37e97129ec29ba9b4a54e5d!]"
  credensial: "ENCRYPTED[!6912fc4e5cb1786a6b6644ebf2be36c65edee9a49ea4561db2365755753644e9ad86e5160e86ff847b871c750abc2dfe!]"
  tokentl: "ENCRYPTED[!9aa257cad95736f4897f178d239e8a6b387011bada0192a6c220f8ce4b97234be111be60eb3e5d43f227e2cefa8cc20c!]"
  idtl: "ENCRYPTED[!4508643dc06e496a5bdef35696637b616238ec9af7111e0efb265d7adbee5a3f5890d487225ccdb1d259b189cf5a567d!]"

task:
  name: "RBE ROM"
  timeout_in: 120m
  container:
    image: ghcr.io/rovars/docker:ubuntu
    cpu: 8
    memory: 32G
    greedy: true

  sync_script:
    - echo "$credensial" > ~/.git-credentials
    - echo "$gitconfigs" > ~/.gitconfig
    - ./main.sh sync
  build_script: ./main.sh build
  upload_script: ./main.sh upload
  rbe_logs_script: cat /tmp/rbe_metrics.txt

  on_failure:
    notiferror_script:
      - xc -x "Build Failed!"
      - xc -c "$SRC_DIR/out/error.log"
      - cat "$SRC_DIR/out/error.log"