env:
  gitconfigs: "ENCRYPTED[!5ac5f7e17bbdc60d88ddde16c0fa3108b36bc9810a169cccde65cd85733cf7a43288ccb2f37e97129ec29ba9b4a54e5d!]"
  credensial: "ENCRYPTED[!6912fc4e5cb1786a6b6644ebf2be36c65edee9a49ea4561db2365755753644e9ad86e5160e86ff847b871c750abc2dfe!]"
  tokentl: "ENCRYPTED[!9aa257cad95736f4897f178d239e8a6b387011bada0192a6c220f8ce4b97234be111be60eb3e5d43f227e2cefa8cc20c!]"
  idtl: "ENCRYPTED[!4508643dc06e496a5bdef35696637b616238ec9af7111e0efb265d7adbee5a3f5890d487225ccdb1d259b189cf5a567d!]"
  rclconfig: "ENCRYPTED[!c2b46109e8c2df2fdc86d269733cf3cad2d659b61508fb4393f7c59a70546dd80eaf640e76620270457b40d3a7bae9d2!]"

task:
  name: "Build"
  timeout_in: 120m
  container:
    image: thisfor/ubuntu:latest
    cpu: 8
    memory: 32G
    greedy: true
  gitconfig_file:
    path: /home/cirrus/.gitconfig
    variable_name: gitconfigs
  credentials_file:
    path: /home/cirrus/.git-credentials
    variable_name: credensial
  rclconfig_file:
    path: /home/cirrus/.rclone.conf
    variable_name: rclconfig
  rcache_background_script: ./build.sh rcache
  sync_script: ./build.sh sync
  build_script: ./build.sh build
  upload_script: ./build.sh upload
  ucache_script: ./build.sh ucache
  on_failure:
    notiferror_script:
       - cat "workdir/out/error.log"
       - sendtl -t "Build Failed!" 
       - sendtl -f "workdir/out/error.log"